import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-specialty-drug-buy-bill-charge-capture",
  "engine": "recovery",
  "title": "Specialty Drug Buy-and-Bill Charge Capture",
  "shortTitle": "Specialty Drug Buy-and-Bill Charge Capture",
  "tagline": "Quantify, recover, and prevent financial leakage through specialty drug buy-and-bill charge capture",
  "industry": "Specialty Drug Revenue Integrity",
  "uiPort": 4596,
  "apiPort": 5596,
  "accent": "#b45309",
  "currency": "USD",
  "primaryOutcome": "Specialty Drug Buy-and-Bill Charge Capture converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect drug purchases, NDC inventory, patient appointments, administrations, NDC-to-HCPCS mappings, units, wastage, authorization, claims, payer rates, and remittances in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "reimbursedAmount",
    "expectedKey": "eligibleAmount",
    "actualLabel": "Captured and Reimbursed Amount",
    "expectedLabel": "Supported Drug Revenue",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Specialty Drug Buy-and-Bill Charge Capture evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("ndc-and-drug-inventory","SDB01","NDC and drug inventory","Execute ndc and drug inventory using drug purchases, NDC inventory, patient appointments, administrations, NDC-to-HCPCS mappings, units, wastage, authorization, claims, payer rates, and remittances.","Produce a governed ndc and drug inventory decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Drug Administration","text","Provider / Drug Administration · Standard Case"],["caseReference","NDC and drug inventory Reference","text","SDB01-2026-001"],["reimbursedAmount","Captured and Reimbursed Amount","currency",512500],["eligibleAmount","Supported Drug Revenue","currency",604750],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["NDC and drug inventory case","Purchase cost ingestion case","Appointment matching case","Administration reconciliation case","NDC-to-HCPCS crosswalk case"]}),
feature("purchase-cost-ingestion","SDB02","Purchase cost ingestion","Execute purchase cost ingestion using drug purchases, NDC inventory, patient appointments, administrations, NDC-to-HCPCS mappings, units, wastage, authorization, claims, payer rates, and remittances.","Produce a governed purchase cost ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Drug Administration","text","Provider / Drug Administration · Standard Case"],["caseReference","Purchase cost ingestion Reference","text","SDB02-2026-001"],["reimbursedAmount","Captured and Reimbursed Amount","currency",512500],["eligibleAmount","Supported Drug Revenue","currency",604750],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["NDC and drug inventory case","Purchase cost ingestion case","Appointment matching case","Administration reconciliation case","NDC-to-HCPCS crosswalk case"]}),
feature("appointment-matching","SDB03","Appointment matching","Execute appointment matching using drug purchases, NDC inventory, patient appointments, administrations, NDC-to-HCPCS mappings, units, wastage, authorization, claims, payer rates, and remittances.","Produce a governed appointment matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Drug Administration","text","Provider / Drug Administration · Standard Case"],["caseReference","Appointment matching Reference","text","SDB03-2026-001"],["reimbursedAmount","Captured and Reimbursed Amount","currency",512500],["eligibleAmount","Supported Drug Revenue","currency",604750],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["NDC and drug inventory case","Purchase cost ingestion case","Appointment matching case","Administration reconciliation case","NDC-to-HCPCS crosswalk case"]}),
feature("administration-reconciliation","SDB04","Administration reconciliation","Execute administration reconciliation using drug purchases, NDC inventory, patient appointments, administrations, NDC-to-HCPCS mappings, units, wastage, authorization, claims, payer rates, and remittances.","Produce a governed administration reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Drug Administration","text","Provider / Drug Administration · Standard Case"],["caseReference","Administration reconciliation Reference","text","SDB04-2026-001"],["reimbursedAmount","Captured and Reimbursed Amount","currency",512500],["eligibleAmount","Supported Drug Revenue","currency",604750],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["NDC and drug inventory case","Purchase cost ingestion case","Appointment matching case","Administration reconciliation case","NDC-to-HCPCS crosswalk case"]}),
feature("ndc-to-hcpcs-crosswalk","SDB05","NDC-to-HCPCS crosswalk","Execute ndc-to-hcpcs crosswalk using drug purchases, NDC inventory, patient appointments, administrations, NDC-to-HCPCS mappings, units, wastage, authorization, claims, payer rates, and remittances.","Produce a governed ndc-to-hcpcs crosswalk decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Drug Administration","text","Provider / Drug Administration · Standard Case"],["caseReference","NDC-to-HCPCS crosswalk Reference","text","SDB05-2026-001"],["reimbursedAmount","Captured and Reimbursed Amount","currency",512500],["eligibleAmount","Supported Drug Revenue","currency",604750],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["NDC and drug inventory case","Purchase cost ingestion case","Appointment matching case","Administration reconciliation case","NDC-to-HCPCS crosswalk case"]}),
feature("j-code-validation","SDB06","J-code validation","Execute j-code validation using drug purchases, NDC inventory, patient appointments, administrations, NDC-to-HCPCS mappings, units, wastage, authorization, claims, payer rates, and remittances.","Produce a governed j-code validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Drug Administration","text","Provider / Drug Administration · Standard Case"],["caseReference","J-code validation Reference","text","SDB06-2026-001"],["reimbursedAmount","Captured and Reimbursed Amount","currency",512500],["eligibleAmount","Supported Drug Revenue","currency",604750],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["NDC and drug inventory case","Purchase cost ingestion case","Appointment matching case","Administration reconciliation case","NDC-to-HCPCS crosswalk case"]}),
feature("unit-conversion-calculation","SDB07","Unit conversion calculation","Execute unit conversion calculation using drug purchases, NDC inventory, patient appointments, administrations, NDC-to-HCPCS mappings, units, wastage, authorization, claims, payer rates, and remittances.","Produce a governed unit conversion calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Drug Administration","text","Provider / Drug Administration · Standard Case"],["caseReference","Unit conversion calculation Reference","text","SDB07-2026-001"],["reimbursedAmount","Captured and Reimbursed Amount","currency",512500],["eligibleAmount","Supported Drug Revenue","currency",604750],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["NDC and drug inventory case","Purchase cost ingestion case","Appointment matching case","Administration reconciliation case","NDC-to-HCPCS crosswalk case"]}),
feature("wastage-modifier-control","SDB08","Wastage modifier control","Execute wastage modifier control using drug purchases, NDC inventory, patient appointments, administrations, NDC-to-HCPCS mappings, units, wastage, authorization, claims, payer rates, and remittances.","Produce a governed wastage modifier control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Drug Administration","text","Provider / Drug Administration · Standard Case"],["caseReference","Wastage modifier control Reference","text","SDB08-2026-001"],["reimbursedAmount","Captured and Reimbursed Amount","currency",512500],["eligibleAmount","Supported Drug Revenue","currency",604750],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["NDC and drug inventory case","Purchase cost ingestion case","Appointment matching case","Administration reconciliation case","NDC-to-HCPCS crosswalk case"]}),
feature("prior-authorization-linkage","SDB09","Prior authorization linkage","Execute prior authorization linkage using drug purchases, NDC inventory, patient appointments, administrations, NDC-to-HCPCS mappings, units, wastage, authorization, claims, payer rates, and remittances.","Produce a governed prior authorization linkage decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Drug Administration","text","Provider / Drug Administration · Standard Case"],["caseReference","Prior authorization linkage Reference","text","SDB09-2026-001"],["reimbursedAmount","Captured and Reimbursed Amount","currency",512500],["eligibleAmount","Supported Drug Revenue","currency",604750],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["NDC and drug inventory case","Purchase cost ingestion case","Appointment matching case","Administration reconciliation case","NDC-to-HCPCS crosswalk case"]}),
feature("payer-reimbursement-calculation","SDB10","Payer reimbursement calculation","Execute payer reimbursement calculation using drug purchases, NDC inventory, patient appointments, administrations, NDC-to-HCPCS mappings, units, wastage, authorization, claims, payer rates, and remittances.","Produce a governed payer reimbursement calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Drug Administration","text","Provider / Drug Administration · Standard Case"],["caseReference","Payer reimbursement calculation Reference","text","SDB10-2026-001"],["reimbursedAmount","Captured and Reimbursed Amount","currency",512500],["eligibleAmount","Supported Drug Revenue","currency",604750],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["NDC and drug inventory case","Purchase cost ingestion case","Appointment matching case","Administration reconciliation case","NDC-to-HCPCS crosswalk case"]}),
feature("missing-charge-detection","SDB11","Missing charge detection","Execute missing charge detection using drug purchases, NDC inventory, patient appointments, administrations, NDC-to-HCPCS mappings, units, wastage, authorization, claims, payer rates, and remittances.","Produce a governed missing charge detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Drug Administration","text","Provider / Drug Administration · Standard Case"],["caseReference","Missing charge detection Reference","text","SDB11-2026-001"],["reimbursedAmount","Captured and Reimbursed Amount","currency",512500],["eligibleAmount","Supported Drug Revenue","currency",604750],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["NDC and drug inventory case","Purchase cost ingestion case","Appointment matching case","Administration reconciliation case","NDC-to-HCPCS crosswalk case"]}),
feature("underpayment-identification","SDB12","Underpayment identification","Execute underpayment identification using drug purchases, NDC inventory, patient appointments, administrations, NDC-to-HCPCS mappings, units, wastage, authorization, claims, payer rates, and remittances.","Produce a governed underpayment identification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Drug Administration","text","Provider / Drug Administration · Standard Case"],["caseReference","Underpayment identification Reference","text","SDB12-2026-001"],["reimbursedAmount","Captured and Reimbursed Amount","currency",512500],["eligibleAmount","Supported Drug Revenue","currency",604750],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["NDC and drug inventory case","Purchase cost ingestion case","Appointment matching case","Administration reconciliation case","NDC-to-HCPCS crosswalk case"]}),
feature("denial-remediation","SDB13","Denial remediation","Execute denial remediation using drug purchases, NDC inventory, patient appointments, administrations, NDC-to-HCPCS mappings, units, wastage, authorization, claims, payer rates, and remittances.","Produce a governed denial remediation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Drug Administration","text","Provider / Drug Administration · Standard Case"],["caseReference","Denial remediation Reference","text","SDB13-2026-001"],["reimbursedAmount","Captured and Reimbursed Amount","currency",512500],["eligibleAmount","Supported Drug Revenue","currency",604750],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["NDC and drug inventory case","Purchase cost ingestion case","Appointment matching case","Administration reconciliation case","NDC-to-HCPCS crosswalk case"]}),
feature("replacement-drug-tracking","SDB14","Replacement drug tracking","Execute replacement drug tracking using drug purchases, NDC inventory, patient appointments, administrations, NDC-to-HCPCS mappings, units, wastage, authorization, claims, payer rates, and remittances.","Produce a governed replacement drug tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Drug Administration","text","Provider / Drug Administration · Standard Case"],["caseReference","Replacement drug tracking Reference","text","SDB14-2026-001"],["reimbursedAmount","Captured and Reimbursed Amount","currency",512500],["eligibleAmount","Supported Drug Revenue","currency",604750],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["NDC and drug inventory case","Purchase cost ingestion case","Appointment matching case","Administration reconciliation case","NDC-to-HCPCS crosswalk case"]}),
feature("drug-payer-and-site-analytics","SDB15","Drug payer and site analytics","Execute drug payer and site analytics using drug purchases, NDC inventory, patient appointments, administrations, NDC-to-HCPCS mappings, units, wastage, authorization, claims, payer rates, and remittances.","Produce a governed drug payer and site analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Drug Administration","text","Provider / Drug Administration · Standard Case"],["caseReference","Drug payer and site analytics Reference","text","SDB15-2026-001"],["reimbursedAmount","Captured and Reimbursed Amount","currency",512500],["eligibleAmount","Supported Drug Revenue","currency",604750],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["NDC and drug inventory case","Purchase cost ingestion case","Appointment matching case","Administration reconciliation case","NDC-to-HCPCS crosswalk case"]})
]);
